package com.kdp.autostudio.service;

import com.kdp.autostudio.config.ConfigManager;
import com.kdp.autostudio.util.ValidationUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Service for packaging and exporting KDP-ready bundles.
 */
public class PackageService {
    private static final Logger logger = LoggerFactory.getLogger(PackageService.class);
    private final ConfigManager configManager;

    public PackageService() {
        this.configManager = ConfigManager.getInstance();
    }

    /**
     * Validate a project and return validation results.
     */
    public ValidationUtil.ValidationResult validateProject(String projectPath) {
        return ValidationUtil.validateProject(projectPath);
    }

    /**
     * Export a project as a KDP-ready ZIP bundle.
     */
    public String exportBundle(String projectPath, String bookTitle) throws IOException {
        // Validate first
        ValidationUtil.ValidationResult validation = validateProject(projectPath);
        if (!validation.isPassed()) {
            throw new IllegalStateException("Project validation failed: " + validation.getErrors());
        }

        String exportsDir = projectPath + File.separator + "exports";
        String zipPath = exportsDir + File.separator + "bundle.zip";

        // Create exports directory if needed
        Files.createDirectories(Paths.get(exportsDir));

        // Create ZIP bundle
        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(zipPath))) {
            // Add interior PDF
            addFileToZip(zos, projectPath + File.separator + "interior" + File.separator + "interior.pdf", "interior.pdf");

            // Add cover PDF
            addFileToZip(zos, projectPath + File.separator + "cover" + File.separator + "cover.pdf", "cover.pdf");

            // Add mockup if exists
            File mockupFile = new File(projectPath + File.separator + "cover" + File.separator + "mockup.png");
            if (mockupFile.exists()) {
                addFileToZip(zos, mockupFile.getAbsolutePath(), "mockup.png");
            }

            // Add metadata if exists
            File metadataFile = new File(projectPath + File.separator + "metadata.json");
            if (metadataFile.exists()) {
                addFileToZip(zos, metadataFile.getAbsolutePath(), "metadata.json");
            }

            // Create readme
            String readmeContent = createReadme(bookTitle);
            addStringToZip(zos, readmeContent, "readme.txt");
        }

        logger.info("Bundle exported to: {}", zipPath);
        return zipPath;
    }

    private void addFileToZip(ZipOutputStream zos, String filePath, String entryName) throws IOException {
        File file = new File(filePath);
        if (!file.exists()) {
            logger.warn("File not found for ZIP: {}", filePath);
            return;
        }

        ZipEntry entry = new ZipEntry(entryName);
        zos.putNextEntry(entry);

        try (FileInputStream fis = new FileInputStream(file)) {
            byte[] buffer = new byte[1024];
            int length;
            while ((length = fis.read(buffer)) > 0) {
                zos.write(buffer, 0, length);
            }
        }

        zos.closeEntry();
    }

    private void addStringToZip(ZipOutputStream zos, String content, String entryName) throws IOException {
        ZipEntry entry = new ZipEntry(entryName);
        zos.putNextEntry(entry);
        zos.write(content.getBytes());
        zos.closeEntry();
    }

    private String createReadme(String bookTitle) {
        return String.format("""
            KDP AutoStudio Export Bundle
            ============================
            
            Book Title: %s
            Generated: %s
            
            Contents:
            - interior.pdf: Book interior file
            - cover.pdf: Book cover file
            - mockup.png: Cover mockup image (if available)
            - metadata.json: KDP metadata (if available)
            
            Instructions:
            1. Upload interior.pdf and cover.pdf to KDP
            2. Use metadata.json for book details
            3. Verify all information before publishing
            
            Generated by KDP AutoStudio
            """, bookTitle, java.time.LocalDateTime.now());
    }
}

